name: Say hello 

on:
  push:
    branches:
      - main

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hello Leo!"
      - name: Give me date
        run: date
      - run: ls -l
