name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name : Deploy
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run eslint
      - name: Create Build
        run: npm run build
      - name: Run Tets
        run: npm test 
          